# Generated by Django 5.1.4 on 2025-02-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cart_products_cart_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
