# Generated by Django 5.1.4 on 2025-02-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_cart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='category',
        ),
    ]
