# Generated by Django 5.1.4 on 2025-02-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(null=True),
        ),
    ]
