# Generated by Django 5.1.4 on 2025-02-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_order_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
